version="0.3.2"

[scripts]

# Database
db="docker run --rm --pull always -p 8000:8000 surrealdb/surrealdb:latest %%"

# Development
css="npx tailwindcss -i ./input.css -o ./public/tailwind.css --watch"
serve="dioxus serve --hot-reload"
