version="0.3.2"

[scripts]
# shortcuts to run app
get-rust="curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
css="npx tailwindcss -i ./input.css -o ./public/tailwind.css --watch"
serve="dioxus serve --hot-reload"

# docker compose