version: '3.0'

services:
  backend:
    command: cargo run 
    env_file:
      - .env
    expose:
      - 5000:5000
    image: backendImage
  frontend:
    command: dioxus serve
    depends_on: 
      - backend
    expose:
      - 8080:8080
    image: frontendImage
